# Generated by Django 3.0.2 on 2020-01-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200119_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
    ]
