# Generated by Django 3.0.2 on 2020-01-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200119_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='details',
            field=models.TextField(default='for testing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.CharField(default='Testing', max_length=255),
            preserve_default=False,
        ),
    ]
